[project]
name = "orray"
version = "0.1.0"
description = "Python package for efficient instantiation of large orthogonal arrays."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"galois",
	"jax",
	"equinox",
	"jaxtyping",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
