[project]
name = "orray"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"numpy",
	"galois",
	"jax[cpu]",
	"equinox",
	"jaxtyping",
	"pytest>=8.4.2",
]
